//app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "./components/UserContext";


export const metadata: Metadata = {
    title: "DPPI BPIP RI",
    description: "Generated by DPPI BPIP RI",
    icons: {
        icon: "/favicon.ico",       // absolut dari root
        shortcut: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="id">
            <head>
                <meta name="robots" content="all" />
                <meta name="googlebot" content="index,follow,all" />
                <meta name="Baiduspider" content="index,follow" />
                <meta name="language" content="bahasa" />
                <meta name="geo.country" content="id" />
                <meta name="geo.placename" content="Indonesia" />
                <meta name="web_author" content="Sekretariat DPPI Pusat" />
                <meta name="author" content="Sekretariat DPPI Pusat" />
                <meta name="keywords" content="DPPI, Duta Pancasila Purnapaskibraka Indonesia, PDP, Purnapaskibraka Duta Pancasila, BPIP, Pancasila, Purna Paskibraka Indonesia, PASKIBRAKA, Badan Pembinaan Ideologi Pancasila , Badan Pembinaan, Ideologi Pancasila" />
                <meta name="description" content="Duta Pancasila Purnapaskibraka Indonesia Badan Pembinaan Ideologi Pancasila Republik Indonesia" />
                <meta property="og:locale" content="id_ID" />
                <meta property="og:type" content="website" />
                <meta property="og:url" content="/" />
                <meta property="og:site_name" content="DPPI BPIP RI - Duta Pancasila Purnapaskibraka Indonesia Badan Pembinaan Ideologi Pancasila Republik Indonesia" />
                <meta property="og:type" content="website" />
                <meta property="og:title" content="DPPI BPIP RI - Duta Pancasila Purnapaskibraka Indonesia Badan Pembinaan Ideologi Pancasila Republik Indonesia" />
                <meta property="og:description" content="Duta Pancasila Purnapaskibraka Indonesia Badan Pembinaan Ideologi Pancasila Republik Indonesia" />
                <meta property="og:keyword" content="DPPI, Duta Pancasila Purnapaskibraka Indonesia, BPIP, Pancasila, Purna Paskibraka Indonesia, PASKIBRAKA, Badan Pembinaan Ideologi Pancasila , Badan Pembinaan, Ideologi Pancasila" />
                <meta property="og:image" content="" />
                <meta property="article:publisher" content="" />
                <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css' />
                <link rel="icon" href="/favicon.ico" sizes="any" />
                <link
                    rel='stylesheet'
                    href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Poppins:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap'
                />

            </head>
            <body className='dark:bg-gray-950'>
                <UserProvider>
                    {children}
                </UserProvider>
            </body>
        </html>
    );
}
